We will be using "default of credit card clients Data Set" from UCI Machine learning repository.


## Imports

In [1]:
%load_ext autotime

In [2]:
import pandas as pd # Pandas for importing data and one hot encoding
import numpy as np # Data manipulation

import matplotlib.pyplot as plt # Plotting, drawing graphs
import matplotlib.colors as colors

from sklearn.utils import resample # downsample the dataset
from sklearn.model_selection import train_test_split # split data into train and test set
from sklearn.preprocessing import scale # scale and center data
from sklearn.svm import SVC # support vector classifier
from sklearn.model_selection import GridSearchCV # this will do cross validation
from sklearn.metrics import confusion_matrix # this creates a confusion matrix
from sklearn.metrics import plot_confusion_matrix # this plots the confusion matrix
from sklearn.decomposition import PCA # decompose and plot the data

from IPython.core.interactiveshell import InteractiveShell # Pretty display of variables
InteractiveShell.ast_node_interactivity = "all"


Bad key savefig.frameon in file /home/amog/.local/lib/python3.6/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle, line 421 ('savefig.frameon : True')
You probably need to get an updated matplotlibrc file from
https://github.com/matplotlib/matplotlib/blob/v3.3.1/matplotlibrc.template
or from the matplotlib source distribution

Bad key verbose.level in file /home/amog/.local/lib/python3.6/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle, line 472 ('verbose.level  : silent      # one of silent, helpful, debug, debug-annoying')
You probably need to get an updated matplotlibrc file from
https://github.com/matplotlib/matplotlib/blob/v3.3.1/matplotlibrc.template
or from the matplotlib source distribution

Bad key verbose.fileo in file /home/amog/.local/lib/python3.6/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle, line 473 ('verbose.fileo  : sys.stdout  # a log filename, sys.stdout or sys.stderr')
You probably need to get an updated matplot

time: 1.2 s


## Read the data

In [3]:
csv_path = "../data/svm/default of credit card clients.xls"

time: 846 µs


In [4]:
df = pd.read_excel(csv_path, header=1)

time: 2.84 s


In [5]:
df.head()

ID  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_0  PAY_2  PAY_3  PAY_4  \
0   1      20000    2          2         1   24      2      2     -1     -1   
1   2     120000    2          2         2   26     -1      2      0      0   
2   3      90000    2          2         2   34      0      0      0      0   
3   4      50000    2          2         1   37      0      0      0      0   
4   5      50000    1          2         1   57     -1      0     -1      0   

   ...  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  PAY_AMT3  \
0  ...          0          0          0         0       689         0   
1  ...       3272       3455       3261         0      1000      1000   
2  ...      14331      14948      15549      1518      1500      1000   
3  ...      28314      28959      29547      2000      2019      1200   
4  ...      20940      19146      19131      2000     36681     10000   

   PAY_AMT4  PAY_AMT5  PAY_AMT6  default payment next month  
0         0         0         0                           1  
1      1000         0      2000                           1  
2      1000      1000      5000                           0  
3      1100      1069      1000                           0  
4      9000       689       679                           0  

[5 rows x 25 columns]

time: 37.2 ms


In [6]:
df.columns

Index(['ID', 'LIMIT_BAL', 'SEX', 'EDUCATION', 'MARRIAGE', 'AGE', 'PAY_0',
       'PAY_2', 'PAY_3', 'PAY_4', 'PAY_5', 'PAY_6', 'BILL_AMT1', 'BILL_AMT2',
       'BILL_AMT3', 'BILL_AMT4', 'BILL_AMT5', 'BILL_AMT6', 'PAY_AMT1',
       'PAY_AMT2', 'PAY_AMT3', 'PAY_AMT4', 'PAY_AMT5', 'PAY_AMT6',
       'default payment next month'],
      dtype='object')

time: 135 ms


ID - Id of the customer <br>
LIMIT_BAL - Credit limit of the customer <br>
SEX - Male(1) / Female(2) <br>
EDUCATION - education (1 = graduate school; 2 = university; 3 = high school; 4 = others) <br>
MARRIAGE - Marital status (1 = married; 2 = single; 3 = others) <br>
AGE - Age (year) <br>
PAY_0 to PAY_6 - History of past payment. We tracked the past monthly payment records (from April to September, 2005), The measurement scale for the repayment status is: -1 = pay duly; 1 = payment delay for one month; 2 = payment delay for two months; . . .; 8 = payment delay for eight months; 9 = payment delay for nine months and above. <br>
BILL_AMT1 to BILL_AMT6 - Amount of bill statement (NT dollar).<br>
PAY_AMT1 to PAY_AMT6 - Amount of previous payment (NT dollar).<br>
default payment next month - Prediction

In [7]:
df.rename({"default payment next month" : "DEFAULT"}, axis='columns', inplace=True)
df.head()

ID  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_0  PAY_2  PAY_3  PAY_4  \
0   1      20000    2          2         1   24      2      2     -1     -1   
1   2     120000    2          2         2   26     -1      2      0      0   
2   3      90000    2          2         2   34      0      0      0      0   
3   4      50000    2          2         1   37      0      0      0      0   
4   5      50000    1          2         1   57     -1      0     -1      0   

   ...  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  PAY_AMT3  \
0  ...          0          0          0         0       689         0   
1  ...       3272       3455       3261         0      1000      1000   
2  ...      14331      14948      15549      1518      1500      1000   
3  ...      28314      28959      29547      2000      2019      1200   
4  ...      20940      19146      19131      2000     36681     10000   

   PAY_AMT4  PAY_AMT5  PAY_AMT6  DEFAULT  
0         0         0         0        1  
1      1000         0      2000        1  
2      1000      1000      5000        0  
3      1100      1069      1000        0  
4      9000       689       679        0  

[5 rows x 25 columns]

time: 160 ms


In [8]:
df.drop("ID", axis=1, inplace=True) # axis = 0 for rows and axis = 1 for columns!
df.head()

LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_0  PAY_2  PAY_3  PAY_4  \
0      20000    2          2         1   24      2      2     -1     -1   
1     120000    2          2         2   26     -1      2      0      0   
2      90000    2          2         2   34      0      0      0      0   
3      50000    2          2         1   37      0      0      0      0   
4      50000    1          2         1   57     -1      0     -1      0   

   PAY_5  ...  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  PAY_AMT3  \
0     -2  ...          0          0          0         0       689         0   
1      0  ...       3272       3455       3261         0      1000      1000   
2      0  ...      14331      14948      15549      1518      1500      1000   
3      0  ...      28314      28959      29547      2000      2019      1200   
4      0  ...      20940      19146      19131      2000     36681     10000   

   PAY_AMT4  PAY_AMT5  PAY_AMT6  DEFAULT  
0         0         0         0        1  
1      1000         0      2000        1  
2      1000      1000      5000        0  
3      1100      1069      1000        0  
4      9000       689       679        0  

[5 rows x 24 columns]

time: 144 ms


## Handle Missing values

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 24 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   LIMIT_BAL  30000 non-null  int64
 1   SEX        30000 non-null  int64
 2   EDUCATION  30000 non-null  int64
 3   MARRIAGE   30000 non-null  int64
 4   AGE        30000 non-null  int64
 5   PAY_0      30000 non-null  int64
 6   PAY_2      30000 non-null  int64
 7   PAY_3      30000 non-null  int64
 8   PAY_4      30000 non-null  int64
 9   PAY_5      30000 non-null  int64
 10  PAY_6      30000 non-null  int64
 11  BILL_AMT1  30000 non-null  int64
 12  BILL_AMT2  30000 non-null  int64
 13  BILL_AMT3  30000 non-null  int64
 14  BILL_AMT4  30000 non-null  int64
 15  BILL_AMT5  30000 non-null  int64
 16  BILL_AMT6  30000 non-null  int64
 17  PAY_AMT1   30000 non-null  int64
 18  PAY_AMT2   30000 non-null  int64
 19  PAY_AMT3   30000 non-null  int64
 20  PAY_AMT4   30000 non-null  int64
 21  PAY_AMT5   3

In [10]:
df.dtypes

LIMIT_BAL    int64
SEX          int64
EDUCATION    int64
MARRIAGE     int64
AGE          int64
PAY_0        int64
PAY_2        int64
PAY_3        int64
PAY_4        int64
PAY_5        int64
PAY_6        int64
BILL_AMT1    int64
BILL_AMT2    int64
BILL_AMT3    int64
BILL_AMT4    int64
BILL_AMT5    int64
BILL_AMT6    int64
PAY_AMT1     int64
PAY_AMT2     int64
PAY_AMT3     int64
PAY_AMT4     int64
PAY_AMT5     int64
PAY_AMT6     int64
DEFAULT      int64
dtype: object

time: 138 ms


This means, NA is not present in any column. But, we should check if they have acceptable values

In [11]:
df["SEX"].unique() # should have only 1/2

array([2, 1])

time: 144 ms


Sex looks good!

Education should have values from 1 to 4, but we see there are extra values - 0, 5, 6 

In [12]:
df["EDUCATION"].unique() 

array([2, 1, 3, 5, 4, 6, 0])

time: 8.71 ms


In [14]:
df.loc[(df["MARRIAGE"] == 0) | (df["EDUCATION"] == 0)]

LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_0  PAY_2  PAY_3  PAY_4  \
218       110000    2          3         0   31      0      0      0      0   
809       160000    2          2         0   37      0      0      0      0   
820       200000    2          3         0   51     -1     -1     -1     -1   
1019      180000    2          3         0   45     -1     -1     -2     -2   
1443      200000    1          3         0   51     -1     -1     -1     -1   
...          ...  ...        ...       ...  ...    ...    ...    ...    ...   
28602     200000    2          3         0   37      1     -1     -1     -1   
28603     110000    2          3         0   44      2      2      2      2   
28766      80000    2          3         0   40      2      2      3      2   
29078     100000    2          3         0   56      1      2      0      0   
29111     300000    2          3         0   53     -2     -2     -2     -2   

       PAY_5  ...  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  \
218        0  ...      73315      63818      63208      4000      5000   
809        0  ...      28574      27268      28021     35888      1325   
820        0  ...        780        390        390         0       390   
1019      -2  ...          0          0          0         0         0   
1443       0  ...       2529       1036       4430      5020      9236   
...      ...  ...        ...        ...        ...       ...       ...   
28602     -1  ...       4000      22800       5716     35000      5000   
28603      2  ...      41476      42090      43059      2000      2000   
28766     -1  ...       1375        779       5889      5000         0   
29078      2  ...      31134      30444      32460         0      1500   
29111     -2  ...          0          0          0         0         0   

       PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6  DEFAULT  
218        3000      3000      3000      8954        0  
809         891      1000      1098       426        0  
820         780         0       390       390        0  
1019          0         0         0         0        0  
1443       2529         0      4430      6398        0  
...         ...       ...       ...       ...      ...  
28602      4000     22800      5716         0        0  
28603      1700      1600      1800      1800        1  
28766         0       885      5889      4239        0  
29078      2700         0      2400         0        0  
29111         0         0         0         0        0  

[68 rows x 24 columns]

time: 29.5 ms


Its just 14 rows in dataset with 30k rows. Lets remove them!

In [15]:
df_no_missing = df.loc[(df["MARRIAGE"] != 0) & (df["EDUCATION"] != 0)]

time: 6.07 ms


In [16]:
len(df_no_missing)

29932

time: 3.36 ms


In [17]:
df_no_missing["MARRIAGE"].unique()

array([1, 2, 3])

time: 4.79 ms


In [18]:
df_no_missing["EDUCATION"].unique()

array([2, 1, 3, 5, 4, 6])

time: 3.83 ms
